name: Build and Publish Strapi Docker Image

on:
  push:
    branches: [main]  # or your preferred branch
    paths:
      - '**/Dockerfile'
      - '**/*.js'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/docker-publish.yml'

      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: PROD
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: optimystic/cms  # replace with your Docker Hub or GHCR image name
      REGISTRY: docker-registry.optimystic.pt

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Logout from Docker
        run: docker logout ${{ env.REGISTRY }}
